apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: soap-service-destination
  namespace: default
spec:
  host: soap-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 60s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
